cc_library(
    name = "collector",
    srcs = [
        "collector.cpp",
        "collector.h"
    ],
    hdrs = [
        "collector.h"
    ],
    deps = [
        "//util/md5:md5",
        "//util/string_utils:string_utils"
    ]
)