cc_library(
    name = "collector",
    srcs = [
        "collector.cpp",
        "collector.h"
    ],
    hdrs = [
        "collector.h"
    ],
    deps = [
        "//util/md5:md5"
    ]
)

# cc_binary(
#     name = "collector_test",
#     srcs = [
#         "collector_test.cpp"
#     ],
#     deps = [
#         "//deliver/collector:collector"
#     ]
# )