cc_library(
    name = "md5",
    srcs = [
        "md5.h",
        "md5.cpp"
    ],
    hdrs = [
        "md5.h"
    ],
    deps = []
)

cc_binary(
    name = "md5_test",
    srcs = [
        "md5_test.cpp"
    ],
    deps = [
        "//util/md5:md5"
    ]
)
