cc_library(
    name = "flags",
    srcs = [
        "flags.cpp",
        "flags.h"
    ],
    hdrs = [
        "flags.h"
    ],
    deps = [
        "//util/string_utils:string_utils"
    ]
)

cc_binary(
    name = "flag_example",
    srcs = [
        "example.cpp"
    ],
    deps = [
        "//util/flags:flags"
    ]
)