cc_library(
    name = "string_utils",
    srcs = [
        "usual.cpp",
        "usual.h",
        "string_utils.h"
    ],
    hdrs = [
        "string_utils.h"
    ],
    deps = [
    ]
)

cc_binary(
    name = "string_utils_example",
    srcs = [
        "example.cpp"
    ],
    deps = [
        "//util/string_utils:string_utils"
    ]
)